Config = {}

Config.OpenMenu = 243
Config.AntiSpamCooldown = 2
Config.Language = {
    Title = "Mochila",
    PleaseWait = "Por favor aguarde ...", 
}

items = {}
items["folhacocamoida"] = {"none", 0 ,0 ,0 , "folhacocamoida.png"}
items["tecidobalistico"] = {"none", 0 ,0 ,0 , "tecido.png"}
items["radio"] = {"none", 0 ,0 ,0 , "radio.png"}
items["cc"] = {"none", 0 ,0 ,0 , "cc.png"}
------
items["partspistol"] = {"none",0 ,0 ,0 , "partspistol.png"}
items["wammopistol"] = {"none",0 ,0 ,0 , "wammopistol.png"}
items["partsminismg"] = {"none",0 ,0 ,0 , "partsminismg.png"}
items["wammominismg"] = {"none",0 ,0 ,0 , "wammopistol.png"}
items["partsassault"] = {"none",0 ,0 ,0 , "partsassault.png"}
items["wammoassault"] = {"none",0 ,0 ,0 , "wammopistol.png"}
------
items["clonado"] = {"none", 0 ,0 ,0 , "acessodeepweb.png"}
items["serra"] = {"none", 0 ,0 ,0 , "serra.png"}
items["furadeira"] = {"none", 0 ,0 ,0 , "furadeira.png"}
items["c4"] = {"none", 0 ,0 ,0 , "c4.png"}
items["ferramenta"] = {"none", 0 ,0 ,0 , "ferramenta.png" }
items["encomenda"] = {"none", 0 ,0 ,0 , "encomenda.png"}
items["falsificados"] = {"none", 0 ,0 ,0 , "encomenda.png"}
items["sacodelixo"] = {"none", 0 ,0 ,0 , "sacodelixo.png"}
items["garrafavazia"] = {"none", 0 ,0 ,0 , "garrafavazia.png"}
items["garrafadeleite"] = {"none", 0 ,0 ,0 , "garrafadeleite.png"}
items["tora"] = {"none", 0 ,0 ,0 , "tora.png"}
items["carbono"] = {"none", 0 ,0 ,0 , "carbono.png"}
items["chumbo"] = {"none", 0 ,0 ,0 , "carbono.png"}
items["aco"] = {"none", 0 ,0 ,0 , "aco.png"}
items["alianca"] = {"none", 0 ,0 ,0 , "alianca.png"}
items["bandagem"] = {"bandagem", 0 ,0 ,0 , "bandagem.png"}
items["pills"] = {"bandagem", 0 ,0 ,0 , "pills.png"}
items["cerveja"] = {"cerveja", 0 ,0 ,0 , "cerveja.png"}
items["tequila"] = {"tequila", 0 ,0 ,0 , "tequila.png"}
items["vodka"] = {"vodka", 0 ,0 ,0 , "vodka.png"}
items["whisky"] = {"whisky", 0 ,0 ,0 , "whisky.png"}
items["conhaque"] = {"conhaque", 0 ,0 ,0 , "conhaque.png"}
items["absinto"] = {"absinto", 0 ,0 ,0 , "absinto.png"}
items["dinheirosujo"] = {"none", 0 ,0 ,0 , "dinheirosujo.png"}
items["malotes"] = {"none", 0 ,0 ,0 , "dinheirosujo.png"}
items["repairkit"] = {"none", 0 ,0 ,0 , "repairkit.png"}
items["algemas"] = {"none", 0 ,0 ,0 , "algemas.png"}
items["capuz"] = {"capuz", 0 ,0 ,0 , "capuz.png"}
items["lockpick"] = {"lockpick", 0 ,0 ,0 , "lockpick.png"}
items["masterpick"] = {"masterpick", 0 ,0 ,0 , "masterpick.png"}
items["militec"] = {"none", 0 ,0 ,0 , "militec.png"}
items["carnedecormorao"] = {"none", 0 ,0 ,0 , "carnedecormorao.png"}
items["carnedecorvo"] = {"none", 0 ,0 ,0 , "carnedecorvo.png"}
items["carnedeaguia"] = {"none", 0 ,0 ,0 , "carnedeaguia.png"}
items["carnedecervo"] = {"none", 0 ,0 ,0 , "carnedecervo.png"}
items["carnedecoelho"] = {"none", 0 ,0 ,0 , "carnedecoelho.png"}
items["carnedecoyote"] = {"none", 0 ,0 ,0 , "carnedecoyote.png"}
items["carnedelobo"] = {"none", 0 ,0 ,0 , "carnedelobo.png"}
items["carnedepuma"] = {"none", 0 ,0 ,0 , "carnedepuma.png"}
items["carnedejavali"] = {"none", 0 ,0 ,0 , "carnedejavali.png"}
items["isca"] = {"none", 0 ,0 ,0 , "isca.png"}
items["dourado"] = {"none", 0 ,0 ,0 , "dourado.png"}
items["corvina"] = {"none", 0 ,0 ,0 , "corvina.png"}
items["salmao"] = {"none", 0 ,0 ,0 , "salmao.png"}
items["pacu"] = {"none", 0 ,0 ,0 , "pacu.png"}
items["pintado"] = {"none", 0 ,0 ,0 , "pintado.png"}
items["pirarucu"] = {"none", 0 ,0 ,0 , "pirarucu.png"}
items["tilapia"] = {"none", 0 ,0 ,0 , "tilapia.png"}
items["tucunare"] = {"none", 0 ,0 ,0 , "tucunare.png"}
items["lambari"] = {"none", 0 ,0 ,0 , "lambari.png"}
items["energetico"] = {"energetico", 0 ,0 ,0 , "energetico.png"}
items["mochila"] = {"mochila", 0 ,0 ,0 , "mochila.png"}
items["macarico"] = {"Maçarico", 0 ,0 ,0 , "macarico.png"}
items["recipientemacarico"] = {"Recipiente Maçarico", 0 ,0 ,0 , "macarico.png"}
items["maconha"] = {"maconha", 0 ,0 ,0 , "maconha.png"}
items["lsd"] = {"lsd", 0 ,0 ,0 , "lsd.png"}
items["crack"] = {"crack", 0 ,0 ,0 , "crack.png"}
items["adubo"] = {"none", 0 ,0 ,0 , "adubo.png"}
items["fertilizante"] = {"none", 0 ,0 ,0 , "fertilizante.png"}
items["capsula"] = {"none", 0 ,0 ,0 , "capsula.png"}
items["polvora"] = {"none", 0 ,0 ,0 , "polvora.png"}
items["orgao"] = {"none", 0 ,0 ,0 , "orgao.png"}
items["etiqueta"] = {"none", 0 ,0 ,0 , "etiqueta.png"}
items["pendrive"] = {"none", 0 ,0 ,0 , "pendrive.png"}
items["relogioroubado"] = {"none", 0 ,0 ,0 , "relogioroubado.png"}
items["pulseiraroubada"] = {"none", 0 ,0 ,0 , "pulseiraroubada.png"}
items["anelroubado"] = {"none", 0 ,0 ,0 , "anelroubado.png"}
items["colarroubado"] = {"none", 0 ,0 ,0 , "colarroubado.png"}
items["brincoroubado"] = {"none", 0 ,0 ,0 , "brincoroubado.png"}
items["folhadecoca"] = {"none", 0 ,0 ,0 , "folhadecocamoida.png"}
items["pastadecoca"] = {"none", 0 ,0 ,0 , "pastadecoca.png"}
items["cocaina"] = {"cocaina", 0 ,0 ,0 , "cocaina.png"}
items["acidobateria"] = {"none", 0 ,0 ,0 , "acidobateria.png"}
items["anfetamina"] = {"none", 0 ,0 ,0 , "anfetamina.png"}
items["ritalina"] = {"none", 0 ,0 ,0 , "ritalina.png"}
items["metanfetamina"] = {"metanfetamina", 0 ,0 ,0 , "metanfetamina.png"}
items["armacaodearma"] = {"none", 0 ,0 ,0 , "armacaodearma.png"}
items["pecadearma"] = {"none", 0 ,0 ,0 , "pecadearma.png"}
items["logsinvasao"] = {"none", 0 ,0 ,0 , "logsinvasao.png"}
items["keysinvasao"] = {"none", 0 ,0 ,0 , "keysinvasao.png"}
items["pendriveinformacoes"] = {"none", 0 ,0 ,0 , "pendriveinformacoes.png"}
items["acessodeepweb"] = {"none", 0 ,0 ,0 , "acessodeepweb.png"}
items["diamante"] = {"none", 0 ,0 ,0 , "diamante.png"}
items["ouro2"] = {"none", 0 ,0 ,0 , "ouro.png"}
items["bronze"] = {"none", 0 ,0 ,0 , "bronze.png"}
items["ferro"] = {"none", 0 ,0 ,0 , "ferro.png"}
items["rubi"] = {"none", 0 ,0 ,0 , "rubi.png"}
items["esmeralda"] = {"none", 0 ,0 ,0 , "esmeralda.png"}
items["safira"] = {"none", 0 ,0 ,0 , "safira.png"}
items["topazio"] = {"none", 0 ,0 ,0 , "topazio.png"}
items["ametista"] = {"none", 0 ,0 ,0 , "ametista.png"}
items["diamante2"] = {"none", 0 ,0 ,0 , "diamante2.png"}
items["ouro"] = {"none", 0 ,0 ,0 , "ouro2.png"}
items["bronze2"] = {"none", 0 ,0 ,0 , "bronze2.png"}
items["ferro2"] = {"none", 0 ,0 ,0 , "ferro2.png"}
items["rubi2"] = {"none", 0 ,0 ,0 , "rubi2.png"}
items["esmeralda2"] = {"none", 0 ,0 ,0 , "esmeralda2.png"}
items["safira2"] = {"none", 0 ,0 ,0 , "safira2.png"}
items["topazio2"] = {"none", 0 ,0 ,0 , "topazio2.png"}
items["ametista2"] = {"none", 0 ,0 ,0 , "ametista2.png"}
items["desfibrilador"] = {"none", 0 ,0 ,0 , "desfibrilador.png"}
items["morfina"] = {"none", 0 ,0 ,0 , "morfina.png"}
items["bicarbonato"] = {"none", 0 ,0 ,0 , "bicarbonato.png"}
items["cloridrato"] = {"none", 0 ,0 ,0 , "cloridrato.png"}
items["acido"] = {"none", 0 ,0 ,0 , "acido.png"}
items["vale"] = {"none", 0 ,0 ,0 , "vip.png"}
------------------------------ARMAS-----------------------------------
items["wbody|WEAPON_COMPACTRIFLE"] = {"weapon", 0 ,0 ,0 , "WEAPON_CARBINERIFLE.png"}
items["wbody|WEAPON_SPECIALCARBINE"] = {"weapon", 0 ,0 ,0 , "WEAPON_CARBINERIFLE.png"}

items["wbody|WEAPON_DAGGER"] = {"weapon", 0 ,0 ,0 , "WEAPON_DAGGER.png"}
items["wbody|WEAPON_BAT"] = {"weapon", 0 ,0 ,0 , "WEAPON_BAT.png"}
items["wbody|WEAPON_BOTTLE"] = {"weapon", 0 ,0 ,0 , "WEAPON_BOTTLE.png"}
items["wbody|WEAPON_CROWBAR"] = {"weapon", 0 ,0 ,0 , "WEAPON_CROWBAR.png"}
items["wbody|WEAPON_FLASHLIGHT"] = {"weapon", 0 ,0 ,0 , "WEAPON_FLASHLIGHT.png"}
items["wbody|WEAPON_GOLFCLUB"] = {"weapon", 0 ,0 ,0 , "WEAPON_GOLFCLUB.png"}
items["wbody|WEAPON_HAMMER"] = {"weapon", 0 ,0 ,0 , "WEAPON_HAMMER.png"}
items["wbody|WEAPON_HATCHET"] = {"weapon", 0 ,0 ,0 , "WEAPON_HATCHET.png"}
items["wbody|WEAPON_KNUCKLE"] = {"weapon", 0 ,0 ,0 , "WEAPON_KNUCKLE.png"}
items["wbody|WEAPON_KNIFE"] = {"weapon", 0 ,0 ,0 , "WEAPON_KNIFE.png"}
items["wbody|WEAPON_MACHETE"] = {"weapon", 0 ,0 ,0 , "WEAPON_MACHETE.png"}
items["wbody|WEAPON_SWITCHBLADE"] = {"weapon", 0 ,0 ,0 , "WEAPON_SWITCHBLADE.png"}
items["wbody|WEAPON_NIGHTSTICK"] = {"weapon", 0 ,0 ,0 , "WEAPON_NIGHTSTICK.png"}
items["wbody|WEAPON_WRENCH"] = {"weapon", 0 ,0 ,0 , "WEAPON_WRENCH.png"}
items["wbody|WEAPON_BATTLEAXE"] = {"weapon", 0 ,0 ,0 , "WEAPON_BATTLEAXE.png"}
items["wbody|WEAPON_POOLCUE"] = {"weapon", 0 ,0 ,0 , "WEAPON_POOLCUE.png"}
items["wbody|WEAPON_STONE_HATCHET"] = {"weapon", 0 ,0 ,0 , "WEAPON_STONE_HATCHET.png"}
items["wbody|WEAPON_PISTOL"] = {"weapon", 0 ,0 ,0 , "WEAPON_PISTOL.png"}
items["wbody|WEAPON_PISTOL_MK2"] = {"weapon", 0 ,0 ,0 , "WEAPON_PISTOL_MK2.png"}
items["wbody|WEAPON_COMBATPISTOL"] = {"weapon", 0 ,0 ,0 , "WEAPON_COMBATPISTOL.png"}
items["wbody|WEAPON_STUNGUN"] = {"weapon", 0 ,0 ,0 , "WEAPON_STUNGUN.png"}
items["wbody|WEAPON_SNSPISTOL"] = {"weapon", 0 ,0 ,0 , "WEAPON_SNSPISTOL.png"}
items["wbody|WEAPON_VINTAGEPISTOL"] = {"weapon", 0 ,0 ,0 , "WEAPON_VINTAGEPISTOL.png"}
items["wbody|WEAPON_REVOLVER"] = {"weapon", 0 ,0 ,0 , "WEAPON_REVOLVER.png"}
items["wbody|WEAPON_MUSKET"] = {"weapon", 0 ,0 ,0 , "WEAPON_MUSKET.png"}
items["wbody|WEAPON_FLARE"] = {"weapon", 0 ,0 ,0 , "WEAPON_FLARE.png"}
items["wbody|GADGET_PARACHUTE"] = {"weapon", 0 ,0 ,0 , "GADGET_PARACHUTE.png"}
items["wbody|WEAPON_FIREEXTINGUISHER"] = {"weapon", 0 ,0 ,0 , "WEAPON_FIREEXTINGUISHER.png"}
items["wbody|WEAPON_MICROSMG"] = {"weapon", 0 ,0 ,0 , "WEAPON_MICROSMG.png"}
items["wbody|WEAPON_SMG"] = {"weapon", 0 ,0 ,0 , "WEAPON_SMG.png"}
items["wbody|WEAPON_ASSAULTSMG"] = {"weapon", 0 ,0 ,0 , "WEAPON_ASSAULTSMG.png"}
items["wbody|WEAPON_COMBATPDW"] = {"weapon", 0 ,0 ,0 , "WEAPON_COMBATPDW.png"}
items["wbody|WEAPON_PUMPSHOTGUN_MK2"] = {"weapon", 0 ,0 ,0 , "WEAPON_PUMPSHOTGUN_MK2.png"}
items["wbody|WEAPON_PETROLCAN"] = {"weapon", 0 ,0 ,0 , "WEAPON_PETROLCAN.png"}
items["wbody|WEAPON_CARBINERIFLE"] = {"weapon", 0 ,0 ,0 , "WEAPON_CARBINERIFLE.png"}
items["wbody|WEAPON_ASSAULTRIFLE"] = {"weapon", 0 ,0 ,0 , "WEAPON_ASSAULTRIFLE.png"}
items["wbody|WEAPON_GUSENBERG"] = {"weapon", 0 ,0 ,0 , "WEAPON_GUSENBERG.png"}

------------------------------Munição-----------------------------------
items["wammo|WEAPON_COMPACTRIFLE"] = {"ammo", 0 ,0 ,0 , "municaorifle.png"}
items["wammo|WEAPON_SPECIALCARBINE"] = {"ammo", 0 ,0 ,0 , "municaorifle.png"}
items["wammo|WEAPON_PISTOL"] = {"ammo",0 ,0 ,0 , "municaopistola.png"}
items["wammo|WEAPON_PISTOL_MK2"] = {"ammo",0 ,0 ,0 , "municaopistola.png"}
items["wammo|WEAPON_COMBATPISTOL"] = {"ammo",0 ,0 ,0 , "municaopistola.png"}
items["wammo|WEAPON_STUNGUN"] = {"ammo",0 ,0 ,0 , "municaotazer.png"}
items["wammo|WEAPON_SNSPISTOL"] = {"ammo",0 ,0 ,0 , "municaopistola.png"}
items["wammo|WEAPON_VINTAGEPISTOL"] = {"ammo",0 ,0 ,0 , "municaopistola.png"}
items["wammo|WEAPON_REVOLVER"] = {"ammo",0 ,0 ,0 , "municaorevolver.png"}
items["wammo|WEAPON_MUSKET"] = {"ammo",0 ,0 ,0 , "municaomosquete.png"}
items["wammo|WEAPON_FLARE"] = {"ammo",0 ,0 ,0 , "municaoflare.png"}
items["wammo|GADGET_PARACHUTE"] = {"ammo",0 ,0 ,0 , "municaoparaquedas.png"}
items["wammo|WEAPON_FIREEXTINGUISHER"] = {"ammo",0 ,0 ,0 , "municaoextintor.png"}
items["wammo|WEAPON_MICROSMG"] = {"ammo",0 ,0 ,0 , "municaopistola.png"}
items["wammo|WEAPON_SMG"] = {"ammo",0 ,0 ,0 , "municaosmg.png"}
items["wammo|WEAPON_ASSAULTSMG"] = {"ammo",0 ,0 ,0 , "municaorifle.png"}
items["wammo|WEAPON_COMBATPDW"] = {"ammo",0 ,0 ,0 , "municaorifle.png"}
items["wammo|WEAPON_PUMPSHOTGUN_MK2"] = {"ammo",0 ,0 ,0 , "municao12.png"}
items["wammo|WEAPON_CARBINERIFLE"] = {"ammo",0 ,0 ,0 , "municaorifle.png"}
items["wammo|WEAPON_ASSAULTRIFLE"] = {"ammo",0 ,0 ,0 , "municaorifle.png"}
items["wammo|WEAPON_GUSENBERG"] = {"ammo",0 ,0 ,0 , "municaorifle.png"}
items["wammo|WEAPON_PETROLCAN"] = {"ammo",0 ,0 ,0 , "gasolina.png"}

items["colete1"] = {"colete",0 ,0 ,0 , "ccc.png"}
items["colete2"] = {"coleteme",0 ,0 ,0 , "ccc.png"}
items["colete3"] = {"coleteus",0 ,0 ,0 , "ccc.png"}

items["tinta"] = {"none",0 ,0 ,0 , "tinta.png"}
items["parts"] = {"none",0 ,0 ,0 , "parts.png"}
items["roupas"] = {"none",0 ,0 ,0 , "roupas.png"}

items["laptop"] = {"none",0 ,0 ,0 , "laptop.png"}
items["c4"] = {"none",0 ,0 ,0 , "c4.png"}
items["barradiamante"] = {"none",0 ,0 ,0 , "barradediamante.png"}
items["barraouro"] = {"none",0 ,0 ,0 , "barradeouro.png"}